export const headers_map = {
  "S NO.": undefined,
  "DISTRICT": "district",
  "STATION": "station",
  "DATE(YYYY-MM-DD)": "date",
  "TIME (UTC)": "time_utc",
  "RAIN FALL CUM. SINCE 0300 UTC (mm)": "rainfall_mm",
  "TEMP. ('C)": "temperature_celcius",
  "TEMP DAY MIN MAX ('C)": undefined,
  "RH (%)": undefined,
  "RH DAY MIN MAX (%)": undefined,
  "WIND DIR 10 m (Deg)": "wind_dir_10m_degree",
  "WIND SPEED 10 m (Kt)": "wind_speed_10m_knots",
  "WIND SPEED MAX / GUST 10 m (Kt)": undefined,
  "WIND DIR 3 m (Deg)": "wind_dir_3m_degree",
  "WIND SPEED 3 m (Kt)": "wind_speed_3m_knots",
  "WIND SPEED MAX / GUST 3 m (Kt)": undefined,
  "SLP (hPa)": "sea_level_pressure_hpa",
  "MSLP (hPa / gpm)": "mean_sea_level_pressure",
  "SUN SHINE (HH.MM)": "sunshine_hh_mm",
  "SOIL TEMP 10 cm ('C)": "soil_temp_at_10cm_depth_celcius",
  "SOIL MOIS 10 cm (m3 / m3)": "soil_moisture_at_10cm_depth_celcius",
  "SOIL TEMP 30 cm ('C)": "soil_temp_at_30cm_depth_celcius",
  "SOIL MOIS 30 cm (m3 / m3)": "soil_moisture_at_30cm_depth_celcius",
  "SOIL TEMP 70 cm ('C)": "soil_temp_at_70cm_depth_celcius",
  "SOIL MOIS 70 cm (m3 / m3)": "soil_moisture_at_70cm_depth_celcius",
  "SOIL TEMP 100 cm ('C)": "soil_temp_at_100cm_depth_celcius",
  "SOIL MOIS 100 cm (m3 / m3)": "soil_moisture_at_100cm_depth_celcius",
  "GLOBAL RAD IATION (v / m2)": "global_radiation",
  "PAR (micro - mole / m2s)": "photo_active_radiation",
  "BATTERY (Volts)": undefined,
  "GPS": undefined,
  "cat_code": "cat_code"
};
